#!/bin/zsh

# AirDrop file and put link in clipboard

if [[ -z $2 ]]; then
    interface='en1';
else
    interface=$2;
fi

if [[ $interface == "--public" ]]; then
    output="curl `curl http://whatismyip.nodejitsu.com/index.txt 2>/dev/null`:5050"
else
    output=`ifconfig $interface | grep inet\ | awk '{print "curl "$2":5050"}'`
fi

output="$output > $1";

echo $output | pbcopy;
cat $1 | nc -l 5050; 
