#!/usr/bin/env python
import datetime
now = datetime.datetime.now()
then = now - datetime.timedelta(days=now.weekday())
then = datetime.datetime(year=then.year, month=then.month, day=then.day, hour=0, minute=0, second=0)
delta = now - then
print "Hours passed: {0}".format(delta.total_seconds() // 3600)
print "Hours left: {0}".format(168 - (delta.total_seconds() // 3600))

